import React, { useState } from "react";

export default function AboutDemo() {
  const [open, setOpen] = useState(true);
  return (
    <div className="card" style={{ padding: 12, borderStyle: "dashed" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8 }}>
        <strong>About this demo</strong>
        <button className="btn" style={{ padding: "4px 8px" }} onClick={() => setOpen(v => !v)}>
          {open ? "Hide" : "Show"}
        </button>
      </div>
      {open && (
        <ul style={{ margin: "8px 0 0 18px", padding: 0 }}>
          <li><b>Rolling Mill context:</b> tracking <i>work-roll temperature</i>, <i>bearing vibration</i>, and <i>line throughput</i>.</li>
          <li><b>How to read it:</b> KPIs show current values; trends show the last ~5 minutes; alerts fire on threshold breaches.</li>
          <li><b>Fake but realistic data:</b> generated by a PLC-style simulator and stored in SQLite.</li>
        </ul>
      )}
    </div>
  );
}
